name: Terraform CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: 'Terraform CI/CD'
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Validate
        if: success() && steps.init.outcome == 'success'
        id: validate
        run: terraform validate

      - name: Terraform Format Check
        if: success() && steps.validate.outcome == 'success'
        id: fmt
        run: terraform fmt -check

      - name: Run tfsec
        if: success() && steps.fmt.outcome == 'success'
        id: tfsec
        uses: aquasecurity/tfsec-action@v1

      - name: Terraform Plan
        if: success() && steps.tfsec.outcome == 'success'
        id: plan
        run: terraform plan -out=tfplan

      - name: Save Plan Output
        if: steps.plan.outputs.stdout != ''
        run: echo "tfplan" > planfile

  apply:
    name: 'Terraform Apply'
    needs: terraform
    runs-on: ubuntu-latest
    if: steps.plan.outputs.stdout != ''
    defaults:
      run:
        working-directory: .

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
