name: Terraform Validation PR

on:
  pull_request:
    branches:
      - main

jobs:
  plan:
    runs-on: ubuntu-latest
    name: 'Terraform Validation'

    strategy:
      matrix:
        environment:
          - name: dev
            path: ./environments/dev
          - name: prod
            path: ./environments/prod

    defaults:
      run:
        working-directory: ${{ matrix.environment.path }}

    steps:
      - name: Run Terraform Steps
        uses: ./.github/workflows/terraform-validate-step.yml
        with:
          environment: ${{ matrix.environment.name }}
          path: ${{ matrix.environment.path }}

    environment: ${{ matrix.environment.name }}